version: "3.7"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    ports:
      - "1433:1433"
    env_file:
      - sqlserver.env
    volumes: 
      - ./sqlsystem/data:/var/opt/mssql/data
      - ./sqldata:/var/opt/sqlserver/data
      - ./sqllog:/var/opt/sqlserver/log
      - ./sqlbackup:/var/opt/sqlserver/backup
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: