version: "3.7"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    ports:
      - "1433:1433"
    env_file:
      - sqlserver.env
    volumes: 
      - ./sqlsystem/data:/var/opt/mssql/data
      - ./sqldata:/var/opt/sqlserver/data
      - ./sqllog:/var/opt/sqlserver/log
      - ./sqlbackup:/var/opt/sqlserver/backup

  mssql_exporter:
    image: awaragi/prometheus-mssql-exporter:latest
    container_name: mssql_exporter
    ports:
      - "332:4000"
    depends_on:
      - sqlserver
    env_file:
      - mssql_exporter.env

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: